### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by jackmac92** [EastCoastProduct/pavlokjs#1]
I was just wondering how I can utilize this to control my own Pavlok. I've been looking around a lot and found the projects from the hack a thon but can't figure out how this would actually be implemented. How do the javascript commands make their way to the Pavlok? Sorry if this is a dumb questions, any tips would be appreciated

**Comment by isvaldo** [comment]
Here we can find doc's ?

**Comment by isvaldo** [comment]
@jackmac92 
See here 
https://pavlok.herokuapp.com/#

You use ObjectId. you just need make a  get request

**Comment by iblazevic** [comment]
we should add at least basic README on this with few examples, we'll make sure to put something in here

**Comment by iblazevic** [comment]
Closing this as on 1.0.1 we updated README with usage examples
